doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: pdo_pgsql
                host: '%env(DATABASE_HOST)%'
                port: '%env(DATABASE_PORT)%'
                user: '%env(DATABASE_USER)%'
                password: '%env(DATABASE_PASSWORD)%'
                dbname: '%env(DATABASE_DBNAME)%'
                server_version: '%env(DATABASE_VERSION)%'
                charset: '%env(DATABASE_CHARSET)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
              is_bundle: false
              dir: '%kernel.project_dir%/src/Entity'
              prefix: 'App\Entity'
              alias: App
              type: attribute